# Generated by Django 3.2.24 on 2024-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media_file',
            field=models.FileField(blank=True, default='../default_post_atyvne', upload_to='posts/'),
        ),
    ]
