# Generated by Django 3.2.24 on 2024-02-24 16:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media_file',
            field=cloudinary.models.CloudinaryField(default='../default_post_atyvne', max_length=255),
        ),
    ]
