# Generated by Django 3.2.24 on 2024-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20240224_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media_file',
            field=models.FileField(blank=True, default='../default_post_atyvne', null=True, upload_to='images/'),
        ),
    ]
