# Generated by Django 3.2.24 on 2024-02-25 09:18

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='media_file',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_atyvne', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='media/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AddConstraint(
            model_name='posts',
            constraint=models.CheckConstraint(check=models.Q(('image__isnull', True), ('video__isnull', True), _connector='OR'), name='only_one_media_allowed'),
        ),
    ]
