# Generated by Django 3.2.24 on 2024-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_posts_only_one_media_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='character_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
