# Generated by Django 3.2.24 on 2024-02-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='owner',
        ),
    ]
