# Generated by Django 3.2.24 on 2024-03-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_user_report_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['resolved', '-created_at']},
        ),
    ]
